name: windows & linux

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.target }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: amd64
            flags: -O3 -fomit-frame-pointer
          - target: x86
            flags: -m32 -O3 -fomit-frame-pointer
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -q -y
          sudo apt-get install -y gcc-multilib g++-multilib valgrind libc6-dbg libc6-dbg:i386
      - name: cmake build & test example
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON ..
            cmake --build .
            ./go_channel
            ./go_sleep
            ./go_select
            ./go_wait_group

  build-windows:
    name: Windows (${{ matrix.arch }})
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - uses: actions/checkout@v3
      - name: cmake build & test examples
        shell: cmd
        run: |
            mkdir build
            cd build
            cmake .. -D BUILD_TESTING=ON -A ${{ matrix.arch }}
            cmake --build . --config Debug
            cd Debug
            .\test_delay.exe 2 5
            .\chan_3.exe
            .\primes.exe
            .\go_channel.exe
            .\go_select.exe
